name: Fetch Exchange Rates

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch: # 手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch Data
      env:
        API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}
      run: |
        curl -s "https://api.exchangerate-api.com/v4/latest/USD?apikey=$API_KEY" > data/latest.json
        
    - name: Commit & Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/latest.json
        git commit -m "Update rates: $(date +'%Y-%m-%d %H:%M')"
        git push
